### ISSUE TITLE
Error adding Regional Transportation Commission of Washoe County

### ISSUE THREAD

**Issue by davidchiles** [transitland/transitland#29]
When trying to submit http://www.rtcwashoe.com/googletransit/latest/google_transit.zip on transit.land I get the `Error with submission` at the final step.

**Comment by drewda** [comment]
Could be an instance of https://github.com/transitland/transitland-datastore/issues/419

**Comment by drewda** [comment]
@davidchiles thanks again for submitting this error report (as well as for all your feed submissions)!

We've deployed a fix that has hopefully solved this issue. If you'd like to retry, please let us know how it goes.

**Comment by davidchiles** [comment]
Still getting the same error.

The server response is `400 Bad Request`

This is the payload for the `POST` request.
```js
{
  "changeset": {
    "notes": "Changed submitted from Feed Registry for feed at http:\/\/www.rtcwashoe.com\/googletransit\/latest\/google_transit.zip",
    "applied": false,
    "applied_at": null,
    "created_at": null,
    "updated_at": null,
    "payload": {
      "changes": [
        {
          "action": "createUpdate",
          "operator": {
            "name": "Regional Transportation Commission of Washoe County",
            "short_name": "RTC RIDE",
            "country": "United States",
            "state": "Nevada",
            "metro": "Washoe County",
            "website": "http:\/\/www.rtcwashoe.com",
            "timezone": "America\/Los_Angeles",
            "geometry": {
              "type": "Polygon",
              "coordinates": [
                [
                  [
                    -119.763382,
                    39.157417
                  ],
                  [
                    -119.896751,
                    39.519375
                  ],
                  [
                    -119.897011,
                    39.647587
                  ],
                  [
                    -119.89698,
                    39.651482
                  ],
                  [
                    -119.896301,
                    39.65477
                  ],
                  [
                    119.813713,
                    39.52734
                  ],
                  [
                    -119.763382,
                    39.157417
                  ]
                ]
              ]
            },
            "tags": {
              "agency_phone": null,
              "agency_lang": null,
              "agency_fare_url": null,
              "agency_id": null
            },
            "onestopId": "o--rtcride"
          }
        },
        {
          "action": "createUpdate",
          "feed": {
            "url": "http:\/\/www.rtcwashoe.com\/googletransit\/latest\/google_transit.zip",
            "onestopId": "f--wwwrtcwashoecom",
            "includesOperators": [
              {
                "gtfsAgencyId": null,
                "operatorOnestopId": "o--rtcride"
              }
            ]
          }
        }
      ]
    },
    "user": {
      "email": "dwalterc@gmail.com",
      "name": "David Chiles",
      "affiliation": null,
      "user_type": "data_enthusiast"
    }
  }
}
```
I'm wondering if there is something wrong with this feed that the server is rejecting?
For example the [geometry](https://gist.github.com/anonymous/f67b16ba03310e05d222) looks incorrect.

**Comment by davidchiles** [comment]
Ran the feed through Google's [transit feed validator](https://github.com/google/transitfeed) and there were 645 warnings. Most because of 'Too Fast Travel'

```
High speed travel detected in trip 306733-1512-1512-Saturday-01: N Virginia/2nd St to Sierra St/W 1st St. 9352719 meters in 60 seconds. (561163 km/h).
```

**Comment by irees** [comment]
hi @davidchiles 

Thank you for helping us find this issue! The geometry is correct, but only because one stop is missing a minus sign on stop_lon (should be -119):

`2040,N Virginia/2nd St,,39.52734,119.813713`

Hopefully this issue can be resolved with the GTFS provider.

This globe-spanning bounding box did identify an issue with our geohash calculation: the 'o--rtcride' in the JSON payload above is missing the second component, the geohash which would normally be something like '9r4b'. I've created an issue to fix this, or at least provide a more useful error message:
https://github.com/transitland/transitland-datastore/issues/430

**Comment by davidchiles** [comment]
Tried the submission again and it seemed to work.
